#+TITLE: Mutation analysis

This directory contains programs for verifying and analyzing our mutation system.

* verify-mutation-parity.rkt
This program verifies that applying the mutation at index =X= to the typed and untyped variants of a benchmark produces the same mutation in both cases.
In other words, it verifies that switching a module from untyped to typed (or vice versa) doesn't change the mutation identified by index =X=.

* analyze-mutation.rkt
This program collects information about how many mutants can be produced for a benchmark, breaks them down by mutator, and whether the mutants produce type errors or not.

* plot-mutation-analyses.rkt
Plots the information collected by [[*analyze-mutation.rkt][analyze-mutation.rkt]].

* summarize-mutation-analyses.rkt
This script generates summaries of the mutations generated by our system.
In particular, it summarizes the mutants that cause type errors and which mutators produced them.

One thing to note about these summaries:
- if a module has no mutants, it just doesn't show up in the summary at all
