#+TITLE: Sampling strategies

* no-sampling.rkt
Just takes every mutant. Simple.

* sample-within-mutators.rkt
This should really be called =use-pre-generated-samples.rkt=. All it does is look up the samples specified in a DB and return them.

This is intended to be used with a script that generates those samples.
Specifically, [[*generate-samples-within-mutators.rkt][generate-samples-within-mutators.rkt]].

* generate-samples-within-mutators.rkt
Generates samples based on [[file:../..//mutation-analysis/readme.org::*summarize-mutation-analyses.rkt][mutation summaries]].
It generates samples with the following strategy:

- Tries to uniformly sample N mutants generated by each mutator.
- Since the input is the total number of mutants desired, T, it calculates
  : N = T / (length active-mutators)
- It samples mutants from the benchmark as a whole, across all of its modules
  + Hence, it's possible to not select any mutants from a given module, due to either
    * there not being any mutants for that module in the first place, or
    * not sampling any mutants within a module
- If no samples are selected in a module, the module just doesn't show up in the sample map
